% Print the curve, base point, and the order of the subgroup.
function PrintEllipticCurveSummary(primeNo, Subgroup, EllipticCurve)
fprintf(['\n(STEP 1) Encryption using eliptic curve y^2 = x^3 + %0.0fx',...
         '+ %0.0f mod %0.0f '], EllipticCurve.a, EllipticCurve.b, ...
         EllipticCurve.p);
fprintf('\n\t... Where %0.0f is the %0.0fth prime number', EllipticCurve.p, ...
        primeNo);
fprintf(['\n\t... And base point (%0.0f, %0.0f) generates a subgroup of ', ...
         'order %0.0f\n'], Subgroup.BasePoint(1), Subgroup.BasePoint(2), ...
         Subgroup.Order)     
end