% Print the encription process.
function PrintEncryptionProcess(message, alicePublicKey, Encryption)
fprintf(['\n(STEP 4) Encrypting message "%s" using Alice''s public ', ...
         'encryption key: \n\t\t k_a * Q= (%0.0f, %0.0f) '], message, ...
         alicePublicKey(1), alicePublicKey(2));
fprintf(['generates the following pairs of points \n\t\t (one set of ', ...
         'points, {(l * Q), (M + l(k_a * Q))}, per letter):\n'])
for i = 1:size(Encryption.Message,2)
    fprintf('\t%2.0f. ''%s'' (Unicode %3.0f), l=%3.0f -> ', i, ...
            message(i), double(message(i)), Encryption.RandInt(i));
    fprintf('{(%3.0f(0, 1)), ((%3.0f, 0) + %3.0f(%3.0f, %3.0f))}', ...
            Encryption.RandInt(i), double(message(i)), Encryption.RandInt(i),...
            alicePublicKey(1), alicePublicKey(2))
    fprintf('\n\t\t = {(%3.0f, %3.0f), (%3.0f, %3.0f)}\n', Encryption.Keys(1,i), ...
            Encryption.Keys(2,i), Encryption.Message(1,i), ...
            Encryption.Message(2,i));
end
end